name: dotnet

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main
  release:
    types:
    - created

jobs:
  dotnet:

    runs-on: ubuntu-latest

    env:
      ENABLE_BENCHMARKS: false

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get specific changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.6
      with:
        files: |
          **/*.yml
          **/*.yaml
          **/*.cs
          **/*.csproj
          **/*.sln
          nuget.config

    - uses: actions/setup-dotnet@v1
      if: ${{ (steps.changed-files.outputs.any_changed == 'true') || (github.event_name == 'release') }}
      with:
        dotnet-version: | 
          5.0.x
          6.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: gittools/actions/gitversion/setup@v0.9.7
      if: ${{ github.event_name == 'release' }}
      with:
        versionSpec: '5.6.10'

    - name: Compute version numbers
      if: ${{ github.event_name == 'release' }}
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: restore dependencies
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: dotnet restore

    - name: Initialize CodeQL
      if: ${{ steps.changed-files.outputs.any_changed == 'true' && github.event_name == 'push' }}
      uses: github/codeql-action/init@v1
      with:
          languages: 'csharp'

    - name: build
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: |
        dotnet build \
          --configuration Release \
          --no-restore \
          /p:UseSharedCompilation=false

    - name: Perform CodeQL Analysis
      if: ${{ steps.changed-files.outputs.any_changed == 'true' && github.event_name == 'push' }}
      uses: github/codeql-action/analyze@v1

    - name: test
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

    - name: retrieve list of coverage info reports
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: echo COVERAGE_REPORTS=$(find ./[Tt]est*/ -name "coverage.info" | paste -sd ";") >> $GITHUB_ENV

    - name: merge code coverage data
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      uses: danielpalme/ReportGenerator-GitHub-Action@4.6.6
      with:
        reports: '${{ env.COVERAGE_REPORTS }}'
        reporttypes: 'lcov'
    
    - name: codecov upload
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov

    - name: publish code coverage results
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      uses: romeovs/lcov-reporter-action@v0.2.21
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coveragereport/lcov.info 

    - name: Create and push package
      if: ${{ github.event_name == 'release' }}
      run: |
        dotnet pack --configuration Release -p:PackageVersion=${{ env.GITVERSION_NUGETVERSIONV2 }} --output .
        dotnet nuget push *.nupkg --skip-duplicate
        dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
    
    - name: Produce `index.md` for gh pages
      # if: ${{ github.event_name == 'release' }}
      run: |
        mkdir out
        echo "version ${{ env.GITVERSION_NUGETVERSIONV2 }}" > out/index.md
        tail -n +4 README.md >> out/index.md
        cat out/index.md
    
    - name: Push chart to dedicated branch
      if: ${{ github.event_name == 'release' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        target_branch: gh-pages
        build_dir: ./out
