name: .NET Core

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main
  release:
    types:
    - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.6.10'

    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          5.0.x
          6.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compute version numbers
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: restore dependencies
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore

    - name: test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

    - name: retrieve list of coverage info reports
      run: echo COVERAGE_REPORTS=$(find ./[Tt]est*/ -name "coverage.info" | paste -sd ";") >> $GITHUB_ENV

    - name: merge code coverage data
      uses: danielpalme/ReportGenerator-GitHub-Action@4.6.6
      with:
        reports: '${{ env.COVERAGE_REPORTS }}'
        reporttypes: 'lcov;HtmlInline'
    
    - name: publish code coverage results
      uses: romeovs/lcov-reporter-action@v0.2.21
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coveragereport/lcov.info 

    - name: create benchmark runners
      run: |
        dotnet publish --no-build benchmarks/Current/Current.csproj --configuration Release -o ./current
        dotnet publish --no-build benchmarks/Previous/Previous.csproj --configuration Release -o ./previous

    - name: run benchmarks
      run: |
        ./previous/Previous
        ./current/Current
    
    - name: previous version benchmark data
      id: previous-benchmark-data
      run: |
        cat BenchmarkDotNet.Artifacts/results/PreviousCompilerBenchmarks-report-github.md

    - name: current version benchmark data
      id: current-benchmark-data
      run: |
        cat BenchmarkDotNet.Artifacts/results/CurrentCompilerBenchmarks-report-github.md

    - uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `
          # Benchmark data
          
          <details>
          <summary>Previous version</summary>
          
          \`\`\`\n
          ${{ previous-benchmark-data }}
          \`\`\`
          
          <summary>Current version</summary>
          
          \`\`\`\n
          ${{ current-benchmark-data }}
          \`\`\`

          </details>
          
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Create package
      if: ${{ env.GITVERSION_NUGETPRERELEASETAGV2 == '' }}
      run: |
        dotnet pack --configuration Release -p:PackageVersion=${{ env.GITVERSION_NUGETVERSIONV2 }} --output .
        dotnet nuget push *.nupkg --skip-duplicate
